[I 09:53:06.974 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 2022-03-14 09:53:08.282 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.282 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.282 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.282 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.282 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.282 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.283 LabApp] 'allow_origin_pat' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.283 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-03-14 09:53:08.283 LabApp] 'jinja_template_vars' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2022-03-14 09:53:08.283 LabApp] 'shutdown_no_activity_timeout' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.283 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 09:53:08.283 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-03-14 09:53:08.293 LabApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 2022-03-14 09:53:08.293 LabApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 09:53:08.305 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 09:53:08.306 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 09:53:08.307 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 09:53:08.307 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 09:53:08.308 NotebookApp] http://jupyter-eldadkeha-2dclass21-2du5k40k9s:8888/user/eldadkeha-class21-u5k40k9s/?token=...
[I 09:53:08.308 NotebookApp]  or http://127.0.0.1:8888/user/eldadkeha-class21-u5k40k9s/?token=...
[I 09:53:08.308 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:53:08.312 NotebookApp] No web browser found: could not locate runnable browser.
[I 09:53:08.314 NotebookApp] 302 GET /user/eldadkeha-class21-u5k40k9s/ (10.244.0.214) 0.930000ms
[I 09:53:09.020 NotebookApp] 302 GET /user/eldadkeha-class21-u5k40k9s/?token=9rHMc8yBRwi8mCprqHa2Tw (82.166.168.241) 1.110000ms
[I 09:53:09.135 NotebookApp] 301 GET /user/eldadkeha-class21-u5k40k9s/lab/?token=9rHMc8yBRwi8mCprqHa2Tw (82.166.168.241) 1.600000ms
[I 09:53:16.321 NotebookApp] 301 GET /user/eldadkeha-class21-u5k40k9s/static/favicons/favicon.ico (82.166.168.241) 0.580000ms
/srv/conda/envs/notebook/lib/python3.7/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 2022-03-14 09:53:19.629 LabApp] Build is up to date
[I 09:54:57.769 NotebookApp] Creating new notebook in 
[I 09:54:57.805 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[I 09:54:59.114 NotebookApp] Kernel started: 272625f7-714a-44c5-bd26-63d10c3b91ff, name: python3
[I 09:54:59.115 NotebookApp] Culling kernels with idle durations > 600 seconds at 60 second intervals ...
[I 09:54:59.115 NotebookApp] Culling kernels even with connected clients
/srv/conda/envs/notebook/lib/python3.7/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 09:55:00.194 NotebookApp] Starting buffering for 272625f7-714a-44c5-bd26-63d10c3b91ff:96f492a2-b343-41a6-af17-e3899871f2f7
[I 09:55:00.596 NotebookApp] 301 GET /user/eldadkeha-class21-u5k40k9s/static/favicons/favicon-busy-1.ico (82.166.168.241) 2.110000ms
[I 09:55:07.761 NotebookApp] Uploading file to /data4.csv
[I 09:55:08.373 NotebookApp] Uploading file to /data3.csv
[I 09:55:36.295 NotebookApp] New terminal with automatic name: 1
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 09:56:58.523 NotebookApp] Saving file at /Untitled.ipynb
[I 09:57:05.535 NotebookApp] Saving file at /requirements.txt
[W 10:06:36.874 NotebookApp] WebSocket ping timeout after 119812 ms.
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
[W 10:07:00.344 NotebookApp] WebSocket ping timeout after 119897 ms.
[W 10:07:00.726 NotebookApp] WebSocket ping timeout after 119899 ms.
[I 10:07:05.728 NotebookApp] Starting buffering for 272625f7-714a-44c5-bd26-63d10c3b91ff:96ae4098-c18f-4455-a480-52eb13e89532
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[W 10:09:59.116 NotebookApp] Culling 'idle' kernel 'python3' (272625f7-714a-44c5-bd26-63d10c3b91ff) with 0 connections due to 650 seconds of inactivity.
[I 10:09:59.117 NotebookApp] Kernel shutdown: 272625f7-714a-44c5-bd26-63d10c3b91ff
[W 10:16:26.217 NotebookApp] WebSocket ping timeout after 119895 ms.
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(41, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(41, 1)>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/management.py", line 239, in pty_read
    client.on_pty_read(s)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 77, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/terminado/websocket.py", line 87, in send_json_message
    self.write_message(json_msg)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/terminal/handlers.py", line 70, in write_message
    super().write_message(message, binary=binary)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[W 10:23:26.716 NotebookApp] WebSocket ping timeout after 119884 ms.
Websocket closed
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
Websocket closed
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 10:42:16.605 NotebookApp] New terminal with automatic name: 2
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
[W 10:53:17.288 NotebookApp] WebSocket ping timeout after 119897 ms.
Websocket closed
[W 10:53:23.120 NotebookApp] WebSocket ping timeout after 119863 ms.
Websocket closed
TermSocket.open: 2
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 2
[I 10:54:05.208 NotebookApp] Creating new notebook in 
[I 10:54:12.267 NotebookApp] Kernel started: d2bc6923-0ce6-46b3-b965-49813b2b8045, name: python3
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
[I 10:56:10.598 NotebookApp] Saving file at /B2.ipynb
[I 10:57:58.961 NotebookApp] Creating new notebook in 
[I 10:58:01.594 NotebookApp] Kernel started: 724baa0e-f45e-4428-933e-66f258c7cb3d, name: python3
[I 10:58:11.061 NotebookApp] Saving file at /B2.ipynb
[I 11:00:00.013 NotebookApp] Saving file at /Untitled.ipynb
[I 11:02:00.297 NotebookApp] Saving file at /Untitled.ipynb
[I 11:02:52.231 NotebookApp] 302 GET /user/eldadkeha-class21-u5k40k9s/ (10.244.0.214) 0.820000ms
[I 11:08:31.809 NotebookApp] Saving file at /B3.ipynb
[W 11:08:59.116 NotebookApp] Culling 'idle' kernel 'python3' (d2bc6923-0ce6-46b3-b965-49813b2b8045) with 1 connections due to 655 seconds of inactivity.
[I 11:08:59.118 NotebookApp] Kernel shutdown: d2bc6923-0ce6-46b3-b965-49813b2b8045
[I 11:09:44.238 NotebookApp] Creating new notebook in 
[I 11:09:51.180 NotebookApp] Kernel started: e39ef500-e0ca-4adb-9812-f74fa7e791ea, name: python3
[I 11:11:51.018 NotebookApp] Saving file at /B4.ipynb
[W 11:18:59.119 NotebookApp] Culling 'idle' kernel 'python3' (724baa0e-f45e-4428-933e-66f258c7cb3d) with 1 connections due to 659 seconds of inactivity.
[I 11:18:59.120 NotebookApp] Kernel shutdown: 724baa0e-f45e-4428-933e-66f258c7cb3d
[W 11:19:59.117 NotebookApp] Culling 'idle' kernel 'python3' (e39ef500-e0ca-4adb-9812-f74fa7e791ea) with 1 connections due to 606 seconds of inactivity.
[I 11:19:59.120 NotebookApp] Kernel shutdown: e39ef500-e0ca-4adb-9812-f74fa7e791ea
[I 11:31:32.121 NotebookApp] Saving file at /B5.ipynb
[I 11:32:21.094 NotebookApp] Copying B5.ipynb to 
[I 11:32:37.354 NotebookApp] Kernel started: 1fdaa518-e7c8-4a9b-aeb5-8a5f26319772, name: python3
[I 11:32:55.103 NotebookApp] Saving file at /B6.ipynb
